<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>stdr_simulator</name>
  <version>0.3.2</version>
  <description>A simple, flexible and scalable 2D multi-robot simulator.</description>

  <maintainer email="zalidis@gmail.com">Chris Zalidis</maintainer>

  <license>GPLv3</license>

  <url type="website">http://stdr-simulator-ros-pkg.github.io</url>
  <url type="bugtracker">https://github.com/stdr-simulator-ros-pkg/stdr_simulator/issues</url>
  <url type="repository">https://github.com/stdr-simulator-ros-pkg/stdr_simulator</url>

  <author>Manos Tsardoulias, Chris Zalidis, Aris Thallas</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>stdr_gui</exec_depend>
  <exec_depend>stdr_gui_ros</exec_depend>
  <exec_depend>stdr_launchers</exec_depend>
  <exec_depend>stdr_msgs</exec_depend>
  <exec_depend>stdr_parser</exec_depend>
  <exec_depend>stdr_resources</exec_depend>
  <exec_depend>stdr_robot</exec_depend>
  <exec_depend>stdr_samples</exec_depend>
  <exec_depend>stdr_server</exec_depend>
  <exec_depend>stdr_simulation</exec_depend>
  <exec_depend>stdr_standalone</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
