<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>stdr_launchers</name>
  <version>1.0.0</version>
  <description>ROS2 launch files for the STDR Simulator.</description>

  <maintainer email="bilal@todo.com">Bilal Gill</maintainer>
  <license>GPL-3.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>stdr_server</exec_depend>
  <exec_depend>stdr_robot</exec_depend>
  <exec_depend>stdr_gui_ros</exec_depend>
  <exec_depend>stdr_resources</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
